/**
 * @copyright Copyright (c) 2023
 * @file lic_platform_device_uuid.cc
 * @author your name (you@domain.com)
 * @brief Get the Platform Device UUID object, the uuid is a string with 64
 * bytes. The uuid is unique for each device. The uuid is generated by the
 * system when the device is installed. The uuid is stored in the system
 * registry on windows, and stored in the file /etc/machine-id on linux, and
 * stored in the system kernel on macos. The uuid is not changed when the
 * device is reinstalled.
 * @version 0.1
 * @date 2023-12-01
 */

#include "lic_platform_device_uuid.h"

#include <stdio.h>
#include <string.h>
#include <stdlib.h>

#if defined(_WIN32) || defined(__CYGWIN__)
#include <windows.h>
#elif defined(__linux__)
#include <unistd.h>
#include <sys/syscall.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <fcntl.h>
#elif defined(__APPLE__)
#include <unistd.h>
#include <sys/sysctl.h>
#endif

/// @brief Get the Platform Device UUID object, the uuid is a string with 64
/// bytes. The uuid is unique for each device. The uuid is generated by the
/// system when the device is installed. The uuid is stored in the system
/// registry on windows, and stored in the file /etc/machine-id on linux, and
/// stored in the system kernel on macos. The uuid is not changed when the
/// device is reinstalled.
/// @param uuid The uuid is a string with 64 bytes.
/// @return int32_t 0: success, -1: failed.
/// @note The uuid is not changed when the device is reinstalled.
int32_t lic_GetPlatformDeviceUUID(uint8_t uuid[1024]) {
      if (uuid == NULL) {
    return -1;
  }

#if defined(_WIN32) || defined(__CYGWIN__)
  HKEY hKey;
  char szUUID[64] = {0};
  DWORD dwSize = 64;
  DWORD dwType = REG_SZ;
  LONG lRet = RegOpenKeyExA(HKEY_LOCAL_MACHINE,
                            "SOFTWARE\\Microsoft\\Cryptography",
                            0, KEY_READ, &hKey);
  if (lRet != ERROR_SUCCESS) {
    return -1;
  }

  lRet = RegQueryValueExA(hKey, "MachineGuid", NULL, &dwType,
                          (LPBYTE)szUUID, &dwSize);
  if (lRet != ERROR_SUCCESS) {
    RegCloseKey(hKey);
    return -1;
  }

  RegCloseKey(hKey);
  memcpy(uuid, szUUID, 64);
#elif defined(__linux__)
  char szUUID[64] = {0};
  int fd = open("/etc/machine-id", O_RDONLY);
  if (fd < 0) {
    return -1;
  }

  if (read(fd, szUUID, sizeof(szUUID)) < 0) {
    close(fd);
    return -1;
  }

  close(fd);
  memcpy(uuid, szUUID, 64);
#elif defined(__APPLE__)
  char szUUID[64] = {0};
  size_t len = sizeof(szUUID);
  if (sysctlbyname("kern.uuid", szUUID, &len, NULL, 0) != 0) {
    return -1;
  }

  memcpy(uuid, szUUID, 64);
#endif

  return 0;
}