/**
 * @copyright Copyright (c) 2023
 * @file lic_verify.c
 * @author hhool (hhool@outlook.com)
 * @brief license certificate verify for third module that generated by license tool.
 * @version 0.1
 * @date 2023-12-01
 */

#include "lic_verify.h"
#include "certificate.h"
#include "lic_machine_cert.h"
#include <string.h>

#define LIC_CERTIFICATE_SIZE (16 * 4)

extern unsigned char g_certificate[LIC_CERTIFICATE_SIZE];

LIC_API void lic_is_activated(int *activated) {
  uint8_t certificate[LIC_CERTIFICATE_SIZE];
  lic_CalculateMachineCert(certificate);
  if (memcmp(certificate, g_certificate, sizeof(g_certificate)) == 0) {
    *activated = TRUE;
  } else {
    *activated = FALSE;
  }
}

